# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20170718_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
