# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170719_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
