# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20170719_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
