# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20170722_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='subject',
            field=models.ManyToManyField(related_name='Details', to='student.Subject'),
        ),
    ]
